services:
  mcp:
    build: .
    container_name: mcp
    ports:
      - 8080:8080
    environment:
      - MCP_HOST=0.0.0.0
      - MCP_PORT=8080
    volumes:
      - ./mcp_data:/data/mcp
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./mongo_data:/data/db

    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=admin
    volumes:
      - ./redis_data:/data