services:
  mongo:
    image: mongo:4.4
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./mongo_data:/data/db
    networks:
      - telegram-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')", "--quiet"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=admin
    volumes:
      - ./redis_data:/data
    networks:
      - telegram-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - 8000:8000
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=FALSE
    volumes:
      - ./chroma_data:/chroma/chroma
    networks:
      - telegram-network
networks:
  telegram-network:
    name: telegram-network
    external: true